[workspace]
authors = ["Wei Ming <alvinwm0523@gmail.com>"]
channels = ["conda-forge"]
name = "mdp"
platforms = ["linux-64","osx-arm64"]
version = "0.1.0"

[tasks]
serve = "zensical serve"
build = "zensical build"

[dependencies]
python = "=3.12"

[pypi-dependencies]
zensical = "*"
